### PR TITLE
fix React warnings about using maps and using keys when listing break…

### LINKED ISSUE #150: Fix: Warning: Using Maps as children
We've had this warning for the past couple weeks. Should be easy to find the component that's using a map.

```
VM3967 bundle.js:2477 Warning: Using Maps as children is not yet fully supported. It is an experimental feature that might be removed. Convert it to a sequence / iterable of keyed ReactElements instead.
```

### PR DESCRIPTION
**Pull request by jlongster**
…points in the editor (fixes #150)

### CODE REVIEW

File: public/js/components/Editor.js [hunk 1]
```diff
@@ -1,28 +1,26 @@
...
 const {
   getSourceText, getPause, getBreakpointsForSource,
-  getSelectedSource, getSelectedSourceOpts
+  getSelectedSource, getSelectedSourceOpts,
+  makeLocationId
 } = require("../selectors");
-
-const { bindActionCreators } = require("redux");
-const { connect } = require("react-redux");
-
```
Comment (jlongster) [inline public/js/components/Editor.js]: All of this is just reordering the imports so they are grouped better.

**Comment by jasonLaster** [comment]
looks good. just CI
